var students = [
    { name: "Đậu Bình An", scores: [2, 6, 8.5] },
    { name: "Từ Thái An", scores: [4, 0, 8] },
    { name: "Dương Việt Anh", scores: [17, 9.5, 12.5] },
    { name: "Nguyễn Công Bách", scores: [13, 0, 10.5] },
    { name: "Nguyễn Hữu Gia Bảo", scores: [13, 3, 10] },
    { name: "Phan Gia Bảo", scores: [5, 3, 2] },
    { name: "Phan Thiện Bảo", scores: [12.5, 2, 5.5] },
    { name: "Võ Tấn Dũng", scores: [12, 10, 16] },
    { name: "Trần Quang Đạo", scores: [12, 4, 13] },
    { name: "Thái Hữu Hoàng Hiếu", scores: [16, 11, 7.75] },
    { name: "Nguyễn Trọng Phi Hoàng", scores: [10, 10, 10.75] },
    { name: "Nguyễn Quang Huy", scores: [11, 4, 11.5] },
    { name: "Nguyễn Gia Hưng", scores: [12, 2, 7] },
    { name: "Thái Gia Hưng", scores: [11, 8, 15.5] },
    { name: "Bùi Danh Khang", scores: [3, 1, 2] },
    { name: "Nguyễn Duy Khánh", scores: [6, 1, 9.5] },
    { name: "Vũ Đình Bảo Khánh", scores: [14, 1, 9] },
    { name: "Nguyễn Vũ Trúc Lâm", scores: [12, 8, 11] },
    { name: "Nguyễn Công Liêm", scores: [10, 5, 10] },
    { name: "Võ Khánh Linh", scores: [13, 2, 8.25] },
    { name: "Giao Minh", scores: [12, 2, 9.75] },
    { name: "Nguyễn Đức Minh", scores: [6, 1, 6] },
    { name: "Tăng Hùng Minh", scores: [4, 6, 9] },
    { name: "Võ Văn Nhật Minh", scores: [12, 1, 11.75] },
    { name: "Nguyễn Xuân Nguyên", scores: [16, 1, 16.5] },
    { name: "Nguyễn Hoàng Phát", scores: [8, 1, 8.25] },
    { name: "Luyện Khánh Phong", scores: [10, 0, 2] },
    { name: "Trần Bảo Phú", scores: [10, 0, 8.25] },
    { name: "Hồ Trung Phúc", scores: [8, 6, 8] },
    { name: "Hồ Mai Phương", scores: [12, 1, 8.5] },
    { name: "Trần Hải Quỳnh", scores: [8, 8, 5.5] },
    { name: "Lê Bảo Sơn", scores: [12, 4, 12] },
    { name: "Bùi Hương Trà", scores: [4, 3, 2] },
    { name: "Trần Nhật Trung", scores: [10, 2, 9] },
    { name: "Võ Hùng Vương", scores: [9.5, 1, 6.5] }
];
